sonar.projectKey=compliance-service
sonar.projectName=compliance-service
sonar.sources=.
sonar.exclusions=**/__pycache__/**, **/*.pyc, **/.venv/**, **/env/**, **/build/**, **/dist/**, **/.tox/**, **/.pytest_cache/**, **/.mypy_cache/**

sonar.sourceEncoding=UTF-8